version: 0.0
os: linux
files:
  - source: app/
    destination: /home/ec2-user/portfolio
hooks:
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 10
  ValidateService:
    - location: scripts/validate.sh
      timeout: 5

