version: 0.0
os: linux
files:
  - source: app/
    destination: /usr/local/portfolio/
hooks:
  BeforeInstall:
    - location: scripts/test.sh
      timeout: 180
  ApplicationStart:
    - location: npm start
      timeout: 10
  ValidateService:
    - location: scripts/validate.sh
      timeout: 5

