---
# tasks file for nodejs
#

- name: Enable epel releases with amazon linux extras
  shell: amazon-linux-extras enable epel
  args:
    executable: /bin/bash

- name: Installing git
  yum:
    name: 'git'
    state: present

- name: Installing nvm
  shell: >-
    git clone https://github.com/nvm-sh/nvm.git
  args:
    chdir: ~

- name: Git checkout latest commit of nvm
  shell: >-
    git checkout v0.34.0
  args:
    chdir: ~/.nvm

- name: Update bashrc for nvm
  lineinfile:
    dest=/home/foo/.bashrc
    line= >-
      export NVM_DIR=\"$HOME/.nvm\"
      [ -s \"$NVM_DIR/nvm.sh\" ] && \. \"$NVM_DIR/nvm.sh\"  # This loads nvm
      [ -s \"$NVM_DIR/bash_completion\" ] && \. \"$NVM_DIR/bash_completion\"  # This loads nvm bash_completion
    owner=ec2-user

- name: Reset ssh connection to allow user changes to affect 'current login user'
  meta: reset_connection

- name: Install latest version of node
  shell: nvm install node
